# Generated by Django 2.2.4 on 2020-03-06 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_auto_20191018_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informes',
            old_name='Bancario',
            new_name='Banco',
        ),
        migrations.RenameField(
            model_name='informes',
            old_name='Beneficios',
            new_name='Deposito',
        ),
        migrations.RenameField(
            model_name='informes',
            old_name='Cantidad',
            new_name='Enviado',
        ),
        migrations.RenameField(
            model_name='informes',
            old_name='Diez',
            new_name='Guiro',
        ),
        migrations.RenameField(
            model_name='informes',
            old_name='Efectivo',
            new_name='Monto_Dolares',
        ),
        migrations.RenameField(
            model_name='informes',
            old_name='Factura',
            new_name='Monto_Pesos',
        ),
        migrations.RenameField(
            model_name='informes',
            old_name='Pedido',
            new_name='Pagos_web',
        ),
        migrations.RenameField(
            model_name='informes',
            old_name='Sesenta',
            new_name='Persona_o_entidad',
        ),
        migrations.RenameField(
            model_name='informes',
            old_name='Tarjeta',
            new_name='Recivido',
        ),
        migrations.RenameField(
            model_name='informes',
            old_name='Total_gastos',
            new_name='simulador_Credito',
        ),
        migrations.RemoveField(
            model_name='informes',
            name='Treinta',
        ),
    ]
