# Generated by Django 2.2.4 on 2020-03-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_auto_20200306_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='informes',
            name='Cuotas_Credito',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='informes',
            name='Monto_Total_credito',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='informes',
            name='Sueldo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='informes',
            name='Banco',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='informes',
            name='Deposito',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='informes',
            name='Enviado',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='informes',
            name='Guiro',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='informes',
            name='Pagos_web',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='informes',
            name='Persona_o_entidad',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='informes',
            name='Recivido',
            field=models.BooleanField(null=True),
        ),
    ]
