# Generated by Django 2.2.4 on 2020-06-25 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_auto_20200306_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informes',
            old_name='Cuotas_Credito',
            new_name='Saldo_Total',
        ),
        migrations.RemoveField(
            model_name='informes',
            name='Banco',
        ),
        migrations.RemoveField(
            model_name='informes',
            name='Deposito',
        ),
        migrations.RemoveField(
            model_name='informes',
            name='Guiro',
        ),
        migrations.RemoveField(
            model_name='informes',
            name='Monto_Dolares',
        ),
        migrations.RemoveField(
            model_name='informes',
            name='Monto_Total_credito',
        ),
        migrations.RemoveField(
            model_name='informes',
            name='Pagos_web',
        ),
        migrations.RemoveField(
            model_name='informes',
            name='Sueldo',
        ),
        migrations.RemoveField(
            model_name='informes',
            name='simulador_Credito',
        ),
    ]
